<?php
use \Illuminate\Foundation\Testing\WithoutMiddleware;

abstract class TestCase extends Illuminate\Foundation\Testing\TestCase
{
    use WithoutMiddleware;
    /**
     * The base URL to use while testing the application.
     *
     * @var string
     */
    protected $baseUrl = 'http://admin.laravel.dev';

    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__ . '/../bootstrap/app.php';

        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

        return $app;
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        Mockery::close();
    }

    public function seeExceptionThrown($exception, $function)
    {
        try {
            $function();
            return false;
        } catch (\Exception $e) {
            if (get_class($e) == $exception) {
                return true;
            }
            return false;
        }
    }

    protected function installInstance($instance) {
        $this->app->instance(get_parent_class($instance), $instance);
    }

    protected function withAuth() {
        $user = factory(\App\Entities\User::class)->make();
        $user->id = 1;
        $this->be($user);
    }
}
